class Car {
  final String tipo;
  final String name;
  final String image;
  final String image2;
  final String logo;
  final String price;
  bool favorite = false;

  Car(this.tipo, this.name, this.price, this.image, this.logo, this.image2);
}

List<Car> cars = [
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CLASSICOS', ' CIVIC', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('ESPORTIVOS', ' mustang', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
  Car('CAMIONETES', ' DOD RAM', '\$520.000', 'imagens/carft3.png',
      'imagens/carft3.png', 'imagens/carft3.png'),
];
